"""add campaigns

Revision ID: 73851af7d0d5
Revises: c393f52626bd
Create Date: 2026-09-17 02:49:51.598970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73851af7d0d5'
down_revision = 'c393f52626bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('audience_type', sa.String(length=30), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_recipients', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_groups',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_groups')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
