"""Add member group relationship

Revision ID: e7b3fb7f1d1f
Revises: af78ca0768a5
Create Date: 2026-09-09 02:56:43.032966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b3fb7f1d1f'
down_revision = 'af78ca0768a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_group',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'group_id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('member_group')
    # ### end Alembic commands ###
